from enum import Enum

__NAMESPACE__ = "urn:hl7-org:v3"


class AddressPartType(Enum):
    ADL = "ADL"
    AL = "AL"
    BNN = "BNN"
    BNR = "BNR"
    BNS = "BNS"
    CAR = "CAR"
    CEN = "CEN"
    CNT = "CNT"
    CPA = "CPA"
    CTY = "CTY"
    DAL = "DAL"
    DEL = "DEL"
    DINST = "DINST"
    DINSTA = "DINSTA"
    DINSTQ = "DINSTQ"
    DIR = "DIR"
    DMOD = "DMOD"
    DMODID = "DMODID"
    INT = "INT"
    POB = "POB"
    PRE = "PRE"
    SAL = "SAL"
    STA = "STA"
    STB = "STB"
    STR = "STR"
    STTYP = "STTYP"
    UNID = "UNID"
    UNIT = "UNIT"
    ZIP = "ZIP"
