from enum import Enum

__NAMESPACE__ = "urn:hl7-org:v3"


class ParticipationType(Enum):
    """vocSet: D10901 (C-0-D10901-cpt)"""
    ADM = "ADM"
    ATND = "ATND"
    CALLBCK = "CALLBCK"
    CON = "CON"
    DIS = "DIS"
    ESC = "ESC"
    REF = "REF"
    IND = "IND"
    BEN = "BEN"
    COV = "COV"
    HLD = "HLD"
    RCT = "RCT"
    RCV = "RCV"
    AUT = "AUT"
    ENT = "ENT"
    INF = "INF"
    WIT = "WIT"
    IRCP = "IRCP"
    NOT = "NOT"
    PRCP = "PRCP"
    REFB = "REFB"
    REFT = "REFT"
    TRC = "TRC"
    PRF = "PRF"
    DIST = "DIST"
    PPRF = "PPRF"
    SPRF = "SPRF"
    DEV = "DEV"
    NRD = "NRD"
    RDV = "RDV"
    SBJ = "SBJ"
    SPC = "SPC"
    DIR = "DIR"
    BBY = "BBY"
    CSM = "CSM"
    DON = "DON"
    PRD = "PRD"
    LOC = "LOC"
    DST = "DST"
    ELOC = "ELOC"
    ORG = "ORG"
    RML = "RML"
    VIA = "VIA"
    VRF = "VRF"
    AUTHEN = "AUTHEN"
    LA = "LA"
    RESP = "RESP"
    CST = "CST"
